
 
lane :build do |options|
    xcodebuild(
        scheme: "QMServices",
        configuration: "Release",
        clean: options[:clean],
        disable_xcpretty: options[:disable_xcpretty],
        build: true,
        destination: "generic/platform=iOS",
        build_settings: {
        "CODE_SIGNING_REQUIRED" => "NO",
            "CODE_SIGN_IDENTITY" => ""
        }
)
end
