lane :build do |options|
    xcodebuild(
        scheme: "QMServices",
        configuration: "Release",
        clean: true,
        skip_build_archive: true,
        disable_xcpretty: false,
        output_directory: "../builds",
        destination: "generic/platform=iOS",
        build_settings: {
        "CODE_SIGNING_REQUIRED" => "NO",
            "CODE_SIGN_IDENTITY" => ""
        }
)
end
